const AccionRedux = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_FROM_CART_REACTREDUX: 'REMOVE_FROM_CART_REACTREDUX',
    GET_USER_API: 'GET_USER_API',
    CHANGE_COLOR: 'CHANGE_COLOR',
}

export default AccionRedux